name: Python Checks
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
    - name: Autoformatter
      run: |
        black --diff .